apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=external-dns-test.internal #search for a specific domain name CAMBIAR!!!!!!
        - --provider=aws-sd #use AWS-SD provider
        - --aws-zone-type=public #search for private namespaces only  CAMBIAR!!!!!!
        - --txt-owner-id=%AWS_Account_ID% #add your AWS account ID as the owner CAMBIAR!!!!!!
        env:
          - name: AWS_REGION
            value: us-east-1 #specify the AWS region  CAMBIAR!!!!!!